
package com.soa.lab4ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdditionalService", targetNamespace = "http://service.lab4ws.soa.com/", wsdlLocation = "http://localhost:8080/lab4-ws-1.0-SNAPSHOT/Additional?wsdl")
public class AdditionalService
    extends Service
{

    private final static URL ADDITIONALSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDITIONALSERVICE_EXCEPTION;
    private final static QName ADDITIONALSERVICE_QNAME = new QName("http://service.lab4ws.soa.com/", "AdditionalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab4-ws-1.0-SNAPSHOT/Additional?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDITIONALSERVICE_WSDL_LOCATION = url;
        ADDITIONALSERVICE_EXCEPTION = e;
    }

    public AdditionalService() {
        super(__getWsdlLocation(), ADDITIONALSERVICE_QNAME);
    }

    public AdditionalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDITIONALSERVICE_QNAME, features);
    }

    public AdditionalService(URL wsdlLocation) {
        super(wsdlLocation, ADDITIONALSERVICE_QNAME);
    }

    public AdditionalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDITIONALSERVICE_QNAME, features);
    }

    public AdditionalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdditionalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdditionalWSI
     */
    @WebEndpoint(name = "AdditionalPort")
    public AdditionalWSI getAdditionalPort() {
        return super.getPort(new QName("http://service.lab4ws.soa.com/", "AdditionalPort"), AdditionalWSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdditionalWSI
     */
    @WebEndpoint(name = "AdditionalPort")
    public AdditionalWSI getAdditionalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.lab4ws.soa.com/", "AdditionalPort"), AdditionalWSI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDITIONALSERVICE_EXCEPTION!= null) {
            throw ADDITIONALSERVICE_EXCEPTION;
        }
        return ADDITIONALSERVICE_WSDL_LOCATION;
    }

}
